name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/pic.jpg
    - images/pork1.jpg
    - images/pork2.jpg
    - images/pork3.jpg
    - images/chick1.jpg
    - images/chick2.jpg
    - images/chick3.jpg
    - images/beef1.jpg
    - images/beef2.jpg
    - images/beef3.jpg
    - images/fish1.jpg
    - images/fish2.jpg
    - images/fish3.jpg
    - images/beef3.jpg
    - images/soda.jpg
    - images/bacon.jpg
    - images/ff.jpg
    - images/ss.jpg







